import { State } from "./state.slint";
export { State }

import { KKRPlayButton, KKRButton } from "./components.slint";
import { KKRTextButton } from "components.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 165px;
    title: "Kokoro";

    VerticalLayout {
        width: parent.width;
        height: parent.height;
        spacing: 0px;

        // background
        Rectangle {
            horizontal-stretch: 1;
            background: #181818;
            clip: true;

            // top
            HorizontalLayout {
                padding: 8px;
                spacing: 8px;

                VerticalLayout {
                    horizontal-stretch: 1;
                    spacing: 2px;
                    alignment: center;

                    Text {
                        text: State.track.artist;
                        color: #999;
                        font-size: 13px;
                        overflow: elide;
                    }

                    Text {
                        text: State.track.title;
                        color: white;
                        font-size: 16px;
                        font-weight: 700;
                        overflow: elide;
                    }
                }
            }
        }

        // separator
        Rectangle {
            height: 1px;
            background: #333;
        }

        // bottom control
        Rectangle {
            height: 48px;
            background: #1a1a1a;

            HorizontalLayout {
                padding-left: 16px;
                alignment: start;
                Text {
                    text: State.current_time_text;
                    color: #999;
                    font-size: 13px;
                    vertical-alignment: center;
                }
            }

            HorizontalLayout {
                padding-left: 8px;
                padding-right: 16px;
                alignment: end;
                spacing: 4px;

                KKRTextButton {
                    icon: "<<";
                    clicked => {
                        State.prev();
                    }
                }

                KKRPlayButton {
                    clicked => {
                        State.play();
                    }
                }

                KKRTextButton {
                    icon: ">>";
                    clicked => {
                        State.next();
                    }
                }
            }
        }
    }
}
