import { KKRState } from "state.slint";

export component KKRButton inherits Rectangle {
    in property <length> size: 32px;

    width: root.size;
    background: transparent;

    callback clicked();

    Rectangle {
        width: root.size;
        height: root.size;
        background: #9d73ec;
    }

    area := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked()
        };
    }
}

export component KKRTextButton inherits KKRButton {
    in property <string> icon: ">";
    Text {
        text: icon;
        font-size: 16px;
        font-weight: 700;
        color: white;
    }
}

export component KKRPlayButton inherits KKRButton {
    Text {
        text: KKRState.playing ? "#" : ">";
        font-size: 16px;
        font-weight: 700;
        color: white;
    }

    area := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked()
        };
    }
}
